# Generated by Django 2.2.7 on 2019-11-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['ee_tag']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='alias',
            field=models.CharField(max_length=60, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ee_tag',
            field=models.CharField(max_length=60, unique=True, verbose_name='EE Tag #'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
